### ISSUE TITLE
Refactor calculator.py

### ISSUE THREAD

**Issue by yeehawbeans** [Veerhan-glitch/Alg#4]
**Issue:**
Calculator.py could be refactored to be more concise.

**Are you willing to submit a PR for this:**
Yes.

**Comment by Veerhan-glitch** [comment]
before i assign u this issue could you pls give a brief info on what you will add

**Comment by yeehawbeans** [comment]
I already wrote the refactor, it's just cleaning up the code and making it more readable, it doesn't change functionality. Feel free to check it out at [https://github.com/B4CKF1SH/Alg/blob/refactor/Calculator.py](https://github.com/B4CKF1SH/Alg/blob/refactor/Calculator.py).

**Comment by Veerhan-glitch** [comment]
Alright pls create a pr so that I can merge ur contribution
